# 1.1 - Numpy (numerical python)

**[Documentación](https://numpy.org/doc/stable/)**

**[Código fuente](https://github.com/numpy/numpy)**


**array**

In [1]:
import numpy as np

In [2]:
# numero

np.array(4)

array(4)

In [3]:
type(np.array(4))

numpy.ndarray

In [4]:
# vector, tensor rango 1

vector=np.random.random(5)  # numeros aleatorios distribuidos uniformemente entre 0 y 1

vector

array([0.39087568, 0.58438466, 0.71728971, 0.82207942, 0.28360302])

In [5]:
type(vector)

numpy.ndarray

In [6]:
# matriz

matriz=np.random.random((10, 4))   # 10 filas 4 columnas

matriz

array([[0.56488447, 0.16140527, 0.54472031, 0.59629863],
       [0.63465687, 0.90296233, 0.24712042, 0.66350727],
       [0.29874605, 0.32513906, 0.64137632, 0.7803085 ],
       [0.04622637, 0.24694567, 0.15733062, 0.79776454],
       [0.85365999, 0.61579458, 0.52270898, 0.43416907],
       [0.50536542, 0.31546537, 0.70723496, 0.71645647],
       [0.15316182, 0.47679814, 0.70358688, 0.0773134 ],
       [0.96595738, 0.63569536, 0.05475948, 0.60318807],
       [0.66396912, 0.74214045, 0.77915619, 0.23141047],
       [0.76666809, 0.59622007, 0.95767534, 0.9946334 ]])

In [7]:
matriz.shape  # dimensiones

(10, 4)

In [8]:
matriz.size   # numero de elemento total

40

In [9]:
len(matriz)

10

In [10]:
type(matriz)

numpy.ndarray

In [11]:
cubo=np.random.random((3, 3, 2))

cubo

array([[[0.39170183, 0.42922052],
        [0.88567204, 0.84931746],
        [0.85673788, 0.54755016]],

       [[0.57731338, 0.88084626],
        [0.48932963, 0.26364854],
        [0.36934452, 0.94976123]],

       [[0.0811413 , 0.36530884],
        [0.54498896, 0.31655962],
        [0.02854464, 0.15424567]]])

In [12]:
cubo.shape

(3, 3, 2)

In [13]:
# tensor de rango 4

tensor=np.random.random((2, 3, 4, 2))

tensor

array([[[[0.32234787, 0.90037284],
         [0.68094157, 0.06417996],
         [0.1065627 , 0.10022161],
         [0.38037995, 0.80381974]],

        [[0.49122975, 0.28477027],
         [0.1943764 , 0.13677492],
         [0.87450573, 0.80941916],
         [0.50339148, 0.06685415]],

        [[0.96498074, 0.04954361],
         [0.55824068, 0.09924602],
         [0.60781039, 0.97191225],
         [0.37083795, 0.5264092 ]]],


       [[[0.53822168, 0.13553258],
         [0.4695039 , 0.50549595],
         [0.55585065, 0.24795924],
         [0.62287478, 0.23486481]],

        [[0.21022933, 0.69844097],
         [0.2051862 , 0.72610105],
         [0.70827   , 0.7918871 ],
         [0.72096461, 0.9168798 ]],

        [[0.87797331, 0.76154227],
         [0.16863157, 0.83453338],
         [0.99764126, 0.55033328],
         [0.92543869, 0.08389561]]]])

In [14]:
tensor.shape

(2, 3, 4, 2)

In [15]:
tensor[0]

array([[[0.32234787, 0.90037284],
        [0.68094157, 0.06417996],
        [0.1065627 , 0.10022161],
        [0.38037995, 0.80381974]],

       [[0.49122975, 0.28477027],
        [0.1943764 , 0.13677492],
        [0.87450573, 0.80941916],
        [0.50339148, 0.06685415]],

       [[0.96498074, 0.04954361],
        [0.55824068, 0.09924602],
        [0.60781039, 0.97191225],
        [0.37083795, 0.5264092 ]]])

In [16]:
tensor[0][2].shape

(4, 2)

In [17]:
tensor[0][2]

array([[0.96498074, 0.04954361],
       [0.55824068, 0.09924602],
       [0.60781039, 0.97191225],
       [0.37083795, 0.5264092 ]])

In [18]:
lst=[2,3,4]

array=np.array(lst)

array

array([2, 3, 4])

In [19]:
lst.shape

AttributeError: 'list' object has no attribute 'shape'

In [21]:
array.shape

(3,)

In [22]:
for e in array:
    print(e)

2
3
4


In [23]:
array.pop()

AttributeError: 'numpy.ndarray' object has no attribute 'pop'

In [24]:
lst_lst=[[2,3,4], [4,7,8]]

array=np.array(lst_lst)

array

array([[2, 3, 4],
       [4, 7, 8]])

In [25]:
array.shape

(2, 3)

**Operaciones matematicas**

In [26]:
matriz

array([[0.56488447, 0.16140527, 0.54472031, 0.59629863],
       [0.63465687, 0.90296233, 0.24712042, 0.66350727],
       [0.29874605, 0.32513906, 0.64137632, 0.7803085 ],
       [0.04622637, 0.24694567, 0.15733062, 0.79776454],
       [0.85365999, 0.61579458, 0.52270898, 0.43416907],
       [0.50536542, 0.31546537, 0.70723496, 0.71645647],
       [0.15316182, 0.47679814, 0.70358688, 0.0773134 ],
       [0.96595738, 0.63569536, 0.05475948, 0.60318807],
       [0.66396912, 0.74214045, 0.77915619, 0.23141047],
       [0.76666809, 0.59622007, 0.95767534, 0.9946334 ]])

In [27]:
matriz.sum()  # suma de todos los elementos

21.682581179972246

In [28]:
np.sum(matriz)

21.682581179972246

In [29]:
matriz.sum(axis=0)  # suma por columnas

array([5.45329557, 5.01856629, 5.3156695 , 5.89504982])

In [30]:
matriz.sum(axis=1)  # suma por filas

array([1.86730867, 2.4482469 , 2.04556993, 1.24826718, 2.42633262,
       2.24452223, 1.41086024, 2.25960029, 2.41667623, 3.31519689])

In [31]:
matriz.sum(axis=2) 

AxisError: axis 2 is out of bounds for array of dimension 2

In [32]:
cubo.sum(axis=2)  # por capas

array([[0.82092235, 1.7349895 , 1.40428804],
       [1.45815964, 0.75297817, 1.31910575],
       [0.44645013, 0.86154858, 0.18279031]])

In [33]:
cubo.sum(axis=1)  # por columnas

array([[2.13411175, 1.82608813],
       [1.43598753, 2.09425603],
       [0.6546749 , 0.83611413]])

In [34]:
cubo.sum(axis=0)  # por filas

array([[1.0501565 , 1.67537561],
       [1.91999063, 1.42952562],
       [1.25462704, 1.65155705]])

In [35]:
cubo

array([[[0.39170183, 0.42922052],
        [0.88567204, 0.84931746],
        [0.85673788, 0.54755016]],

       [[0.57731338, 0.88084626],
        [0.48932963, 0.26364854],
        [0.36934452, 0.94976123]],

       [[0.0811413 , 0.36530884],
        [0.54498896, 0.31655962],
        [0.02854464, 0.15424567]]])

In [36]:
matriz

array([[0.56488447, 0.16140527, 0.54472031, 0.59629863],
       [0.63465687, 0.90296233, 0.24712042, 0.66350727],
       [0.29874605, 0.32513906, 0.64137632, 0.7803085 ],
       [0.04622637, 0.24694567, 0.15733062, 0.79776454],
       [0.85365999, 0.61579458, 0.52270898, 0.43416907],
       [0.50536542, 0.31546537, 0.70723496, 0.71645647],
       [0.15316182, 0.47679814, 0.70358688, 0.0773134 ],
       [0.96595738, 0.63569536, 0.05475948, 0.60318807],
       [0.66396912, 0.74214045, 0.77915619, 0.23141047],
       [0.76666809, 0.59622007, 0.95767534, 0.9946334 ]])

In [37]:
matriz.min()   # minimo absoluto

0.046226365410877324

In [38]:
matriz.min(axis=0)

array([0.04622637, 0.16140527, 0.05475948, 0.0773134 ])

In [39]:
matriz.max(axis=0)  # maximo por columna

array([0.96595738, 0.90296233, 0.95767534, 0.9946334 ])

In [40]:
matriz.mean()   # media de todos los elementos

0.5420645294993062

In [41]:
matriz.mean(axis=0)

array([0.54532956, 0.50185663, 0.53156695, 0.58950498])

In [42]:
np.median(matriz)

0.5997433510674395

In [43]:
matriz.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [44]:
np.median(matriz, axis=0)

array([0.59977067, 0.5365091 , 0.59304832, 0.63334767])

In [45]:
matriz.std()  # desviacion estandar

0.2645223260626935

In [46]:
matriz.std(axis=0) 

array([0.28438062, 0.22492369, 0.27639401, 0.26085141])

In [47]:
matriz.var()

0.06997206098561794

In [48]:
matriz.var() ** 0.5

0.2645223260626935

In [49]:
v1=matriz[0]

In [50]:
v2=matriz[1]

In [51]:
v1, v2

(array([0.56488447, 0.16140527, 0.54472031, 0.59629863]),
 array([0.63465687, 0.90296233, 0.24712042, 0.66350727]))

In [52]:
np.add(v1, v2)  # suma de vectores, elemento a elemento (element wise)

array([1.19954134, 1.06436759, 0.79184073, 1.25980591])

In [53]:
np.subtract(v1, v2)  # resta de vectores

array([-0.0697724 , -0.74155706,  0.29759988, -0.06720864])

In [54]:
np.prod(matriz)

5.821986800821896e-15

In [55]:
1e3    # notacion cientifica

1000.0

In [56]:
1e-3

0.001

In [57]:
np.multiply(v1, v2)  # producto elemento a elemento

array([0.35850781, 0.14574287, 0.13461151, 0.39564848])

In [58]:
np.dot(v1, v2)   # producto escalar

1.0345106759154332

In [59]:
np.cross(v1[:3], v2[:3])    # producto vectorial, producto aspa

array([-0.45197538,  0.206116  ,  0.40763243])

In [60]:
matriz.T   # matriz traspuesta

array([[0.56488447, 0.63465687, 0.29874605, 0.04622637, 0.85365999,
        0.50536542, 0.15316182, 0.96595738, 0.66396912, 0.76666809],
       [0.16140527, 0.90296233, 0.32513906, 0.24694567, 0.61579458,
        0.31546537, 0.47679814, 0.63569536, 0.74214045, 0.59622007],
       [0.54472031, 0.24712042, 0.64137632, 0.15733062, 0.52270898,
        0.70723496, 0.70358688, 0.05475948, 0.77915619, 0.95767534],
       [0.59629863, 0.66350727, 0.7803085 , 0.79776454, 0.43416907,
        0.71645647, 0.0773134 , 0.60318807, 0.23141047, 0.9946334 ]])

In [61]:
matriz.transpose()

array([[0.56488447, 0.63465687, 0.29874605, 0.04622637, 0.85365999,
        0.50536542, 0.15316182, 0.96595738, 0.66396912, 0.76666809],
       [0.16140527, 0.90296233, 0.32513906, 0.24694567, 0.61579458,
        0.31546537, 0.47679814, 0.63569536, 0.74214045, 0.59622007],
       [0.54472031, 0.24712042, 0.64137632, 0.15733062, 0.52270898,
        0.70723496, 0.70358688, 0.05475948, 0.77915619, 0.95767534],
       [0.59629863, 0.66350727, 0.7803085 , 0.79776454, 0.43416907,
        0.71645647, 0.0773134 , 0.60318807, 0.23141047, 0.9946334 ]])

In [62]:
np.matmul(matriz, matriz.T)    # producto matricial

array([[0.99743839, 1.03451068, 1.03590376, 0.62737797, 1.12523637,
        1.14885811, 0.5928364 , 1.03776772, 1.05726317, 1.64407569],
       [1.03451068, 1.71944072, 1.15942711, 0.8205227 , 1.51506689,
        1.25573327, 0.75290465, 1.60081231, 1.43760537, 1.92154306],
       [1.03590376, 1.15942711, 1.21520955, 0.8175122 , 1.1292854 ,
        1.26620687, 0.71237446, 1.00105956, 1.11996089, 1.81324467],
       [0.62737797, 0.8205227 , 0.8175122 , 0.72430022, 0.62013221,
        0.78409729, 0.297197  , 0.69145231, 0.52115744, 1.12682914],
       [1.12523637, 1.51506689, 1.1292854 , 0.62013221, 1.5696658 ,
        1.30641341, 0.82569609, 1.5065658 , 1.53155314, 1.95404751],
       [1.14885811, 1.25573327, 1.26620687, 0.78409729, 1.30641341,
        1.36840378, 0.78080892, 1.15958715, 1.28650868, 1.96544734],
       [0.5928364 , 0.75290465, 0.71237446, 0.297197  , 0.82569609,
        0.78080892, 0.75180687, 0.53620873, 1.02164111, 1.15240719],
       [1.03776772, 1.60081231, 1.0010595

In [63]:
np.dot(matriz, matriz.T) 

array([[0.99743839, 1.03451068, 1.03590376, 0.62737797, 1.12523637,
        1.14885811, 0.5928364 , 1.03776772, 1.05726317, 1.64407569],
       [1.03451068, 1.71944072, 1.15942711, 0.8205227 , 1.51506689,
        1.25573327, 0.75290465, 1.60081231, 1.43760537, 1.92154306],
       [1.03590376, 1.15942711, 1.21520955, 0.8175122 , 1.1292854 ,
        1.26620687, 0.71237446, 1.00105956, 1.11996089, 1.81324467],
       [0.62737797, 0.8205227 , 0.8175122 , 0.72430022, 0.62013221,
        0.78409729, 0.297197  , 0.69145231, 0.52115744, 1.12682914],
       [1.12523637, 1.51506689, 1.1292854 , 0.62013221, 1.5696658 ,
        1.30641341, 0.82569609, 1.5065658 , 1.53155314, 1.95404751],
       [1.14885811, 1.25573327, 1.26620687, 0.78409729, 1.30641341,
        1.36840378, 0.78080892, 1.15958715, 1.28650868, 1.96544734],
       [0.5928364 , 0.75290465, 0.71237446, 0.297197  , 0.82569609,
        0.78080892, 0.75180687, 0.53620873, 1.02164111, 1.15240719],
       [1.03776772, 1.60081231, 1.0010595

In [64]:
np.dot(matriz, matriz.T).shape

(10, 10)

In [65]:
matriz.cumsum()[-1]    # suma acumulada, sumatorio

21.682581179972246

In [66]:
matriz.cumprod()[-1]   # producto acumulado, productorio

5.821986800821896e-15

In [67]:
type(np.inf)   # el infinito

float

**Dimensiones**

In [68]:
matriz.shape

(10, 4)

In [69]:
matriz.T.shape

(4, 10)

In [70]:
matriz.reshape((40, ))    # redimensionar a proposito, con las dimensiones

array([0.56488447, 0.16140527, 0.54472031, 0.59629863, 0.63465687,
       0.90296233, 0.24712042, 0.66350727, 0.29874605, 0.32513906,
       0.64137632, 0.7803085 , 0.04622637, 0.24694567, 0.15733062,
       0.79776454, 0.85365999, 0.61579458, 0.52270898, 0.43416907,
       0.50536542, 0.31546537, 0.70723496, 0.71645647, 0.15316182,
       0.47679814, 0.70358688, 0.0773134 , 0.96595738, 0.63569536,
       0.05475948, 0.60318807, 0.66396912, 0.74214045, 0.77915619,
       0.23141047, 0.76666809, 0.59622007, 0.95767534, 0.9946334 ])

In [71]:
matriz.flatten()    # aplanar la matriz, convertir en lista

array([0.56488447, 0.16140527, 0.54472031, 0.59629863, 0.63465687,
       0.90296233, 0.24712042, 0.66350727, 0.29874605, 0.32513906,
       0.64137632, 0.7803085 , 0.04622637, 0.24694567, 0.15733062,
       0.79776454, 0.85365999, 0.61579458, 0.52270898, 0.43416907,
       0.50536542, 0.31546537, 0.70723496, 0.71645647, 0.15316182,
       0.47679814, 0.70358688, 0.0773134 , 0.96595738, 0.63569536,
       0.05475948, 0.60318807, 0.66396912, 0.74214045, 0.77915619,
       0.23141047, 0.76666809, 0.59622007, 0.95767534, 0.9946334 ])

In [72]:
matriz.reshape((20, 2))

array([[0.56488447, 0.16140527],
       [0.54472031, 0.59629863],
       [0.63465687, 0.90296233],
       [0.24712042, 0.66350727],
       [0.29874605, 0.32513906],
       [0.64137632, 0.7803085 ],
       [0.04622637, 0.24694567],
       [0.15733062, 0.79776454],
       [0.85365999, 0.61579458],
       [0.52270898, 0.43416907],
       [0.50536542, 0.31546537],
       [0.70723496, 0.71645647],
       [0.15316182, 0.47679814],
       [0.70358688, 0.0773134 ],
       [0.96595738, 0.63569536],
       [0.05475948, 0.60318807],
       [0.66396912, 0.74214045],
       [0.77915619, 0.23141047],
       [0.76666809, 0.59622007],
       [0.95767534, 0.9946334 ]])

In [73]:
matriz=np.random.random((20, 3))   # matriz de 20x3 con numeros entere 0 y 1

matriz

array([[0.04370967, 0.66948833, 0.61062024],
       [0.49635795, 0.94415394, 0.85984226],
       [0.77928242, 0.44368142, 0.55852551],
       [0.15948875, 0.78451053, 0.14099423],
       [0.98430749, 0.38323413, 0.98068504],
       [0.69123445, 0.67135661, 0.33326616],
       [0.37398047, 0.99614935, 0.42474268],
       [0.93305891, 0.90758006, 0.04412411],
       [0.83186516, 0.5704741 , 0.86322272],
       [0.55765097, 0.63724047, 0.00725724],
       [0.10212181, 0.09940909, 0.80584864],
       [0.71427913, 0.82486653, 0.32691777],
       [0.05750261, 0.21790622, 0.63429055],
       [0.9023375 , 0.05564282, 0.70522701],
       [0.98310556, 0.78333359, 0.53491334],
       [0.26775636, 0.90533115, 0.15175889],
       [0.46825046, 0.63572374, 0.6343884 ],
       [0.43491027, 0.19129017, 0.51607149],
       [0.96125742, 0.52133437, 0.75540719],
       [0.31115172, 0.40388959, 0.37306146]])

In [74]:
matriz.reshape((3, 2, 10))

array([[[0.04370967, 0.66948833, 0.61062024, 0.49635795, 0.94415394,
         0.85984226, 0.77928242, 0.44368142, 0.55852551, 0.15948875],
        [0.78451053, 0.14099423, 0.98430749, 0.38323413, 0.98068504,
         0.69123445, 0.67135661, 0.33326616, 0.37398047, 0.99614935]],

       [[0.42474268, 0.93305891, 0.90758006, 0.04412411, 0.83186516,
         0.5704741 , 0.86322272, 0.55765097, 0.63724047, 0.00725724],
        [0.10212181, 0.09940909, 0.80584864, 0.71427913, 0.82486653,
         0.32691777, 0.05750261, 0.21790622, 0.63429055, 0.9023375 ]],

       [[0.05564282, 0.70522701, 0.98310556, 0.78333359, 0.53491334,
         0.26775636, 0.90533115, 0.15175889, 0.46825046, 0.63572374],
        [0.6343884 , 0.43491027, 0.19129017, 0.51607149, 0.96125742,
         0.52133437, 0.75540719, 0.31115172, 0.40388959, 0.37306146]]])